version: '3.8'
services:
  frontend:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - VITE_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - VITE_AGORA_APP_ID=${AGORA_APP_ID}
    volumes:
      - ../../:/app
      - /app/node_modules
    command: npm run dev

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
