name: Performance Monitoring

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily

jobs:
  performance:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v12
      with:
        urls: |
          ${{ secrets.PRODUCTION_URL }}
        uploadArtifacts: true
        temporaryPublicStorage: true
        configPath: './.github/lighthouse/config.json'
        
    - name: Run bundle-analyzer
      run: npx vite-bundle-analyzer dist/stats.json
      
    - name: Upload bundle analysis
      uses: actions/upload-artifact@v4
      with:
        name: bundle-analysis
        path: bundle-analysis.html
