name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_LOAD_SERVICE_URL: ${{ secrets.VITE_LOAD_SERVICE_URL }}
        VITE_QUOTE_SERVICE_URL: ${{ secrets.VITE_QUOTE_SERVICE_URL }}
        VITE_SHIPMENT_SERVICE_URL: ${{ secrets.VITE_SHIPMENT_SERVICE_URL }}
        VITE_CARRIER_SERVICE_URL: ${{ secrets.VITE_CARRIER_SERVICE_URL }}
        VITE_MESSAGE_SERVICE_URL: ${{ secrets.VITE_MESSAGE_SERVICE_URL }}
        VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
    
    - name: Generate changelog
      id: changelog
      uses: conventional-changelog/conventional-changelog-action@v4.1.0
      with:
        config: conventional-changelog-conventionalcommits
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        body: ${{ steps.changelog.outputs.changelog }}
        files: |
          dist/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Deploy to Production
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'lanerunner'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './dist'
    
    - name: Notify on Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
